---
# tasks file for apache
- name: Install the latest version of Apache
  ansible.builtin.dnf:
    name: httpd
    state: latest
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: "0644"
- name: Start and enable httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
